[package]
name = "wasabi"
version = "0.1.0"
authors = ["sinsoku <sinsoku.listy@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rb-sys = "0.9"
rb-allocator = "0.9"
magnus = { version = "0.3", features = ["rb-sys-interop"] }
